function [signal, frequency] = generate_random_signal(...
    time,...
    frequency_range,...
    amplitude_range,...
    phase_range,...
    random_state...
)
    if nargin < 5 || isempty(random_state)
        random_state = randi(2^31 - 1);
    end
    rng(random_state);
    
    amplitude = unifrnd(amplitude_range(1), amplitude_range(2));
    frequency = unifrnd(frequency_range(1), frequency_range(2));
    theta = unifrnd(phase_range(1), phase_range(2));
    
    signal = amplitude * sin(2*pi*frequency*time + theta);
end