addpath ../data_generation
disp(path)
num_signals = 10;
num_data_points = 1000;
num_components_range = [5 5];
sampling_freq = 1000;
freq_range = [2 100];
amplitude_range = [1 5];
phase_range = [0 1];
signal_to_noise_ratio = 0.1;
random_state = 101;
intermittent_prob = 0.33;
combined_prob = 0.33;
allow_intermittent = true;
allow_combined = true;
allow_multiple_intermittent = true;
allow_multiple_combined = true;

% You can load the dataset instead of generating from scratch
% dataset = Dataset.load();

if isempty(dataset)
    disp("Generating data...")
    generator = SimpleGenerator(...
        num_signals,...
        num_data_points,...
        num_components_range,...
        sampling_freq,...
        freq_range,...
        amplitude_range,...
        phase_range,...
        signal_to_noise_ratio,...
        random_state,...
        intermittent_prob,...
        combined_prob,...
        allow_intermittent,...
        allow_combined,...
        allow_multiple_intermittent,...
        allow_multiple_combined...
    );

    dataset = generator.generate_dataset([500 500]);

    % Save dataset if needed (including the generator to save its parameters)
    dataset.save();

    % Alternatively, we can save the data only
    dataset.save_data()
end

dataset.plot()